spring:
  application:
    name: hello-codespaces
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  forward-headers-strategy: NATIVE